
Pays = {"Afghanistan":"AFG",
        "Albania":"ALB",
        "Algeria":"ALG",
        "Andorra":"AND",
        "Angola":"ANG",
        "Antigua and Barbuda":"ANT",
        "Argentina":"ARG",
        "Armenia":"ARM",
        "Aruba":"ARU",
        "American Samoa":"ASA",
        "Australia":"AUS",
        "Austria":"AUT",
        "Azerbaijan":"AZE",
        "Bahamas":"BAH",
        "Bangladesh":"BAN",
        "Barbados":"BAR",
        "Burundi":"BDI",
        "Belgium":"BEL",
        "Benin":"BEN",
        "Bermuda":"BER",
        "Bhutan":"BHU",
        "Bosnia and Herzegovina":"BIH",
        "Belize":"BIZ",
        "Belarus":"BLR",
        "Bolivia":"BOL",
        "Botswana":"BOT",
        "Brazil":"BRA",
        "Bahrain":"BRN",
        "Brunei":"BRU",
        "Bulgaria":"BUL",
        "Burkina Faso":"BUR",
        "Central African Republic":"CAF",
        "Cambodia":"CAM",
        "Canada":"CAN",
        "Cayman Islands":"CAY",
        "Congo":"CGO",
        "Chad":"CHA",
        "Chile":"CHI",
        "China":"CHN",
        "Ivory Coast":"CIV",
        "Cameroon":"CMR",
        "DR Congo":"COD",
        "Cook Islands":"COK",
        "Colombia":"COL",
        "Comoros":"COM",
        "Cape Verde":"CPV",
        "Costa Rica":"CRC",
        "Croatia":"CRO",
        "Cuba":"CUB",
        "Cyprus":"CYP",
        "Czech Republic":"CZE",
        "Denmark":"DEN",
        "Djibouti":"DJI",
        "Dominica":"DMA",
        "Dominican Republic":"DOM",
        "Ecuador":"ECU",
        "Egypt":"EGY",
        "Eritrea":"ERI",
        "El Salvador":"ESA",
        "Spain":"ESP",
        "Estonia":"EST",
        "Ethiopia":"ETH",
        "Fiji":"FIJ",
        "Finland":"FIN",
        "France":"FRA",
        "Federated States of Micronesia":"FSM",
        "Gabon":"GAB",
        "The Gambia":"GAM",
        "Great Britain":"GBR",
        "Guinea-Bissau":"GBS",
        "Georgia":"GEO",
        "Equatorial Guinea":"GEQ",
        "Germany":"GER",
        "Ghana":"GHA",
        "Greece":"GRE",
        "Grenada":"GRN",
        "Guatemala":"GUA",
        "Guinea":"GUI",
        "Guam":"GUM",
        "Guyana":"GUY",
        "Haiti":"HAI",
        "Hong Kong":"HKG",
        "Honduras":"HON",
        "Hungary":"HUN",
        "Indonesia":"INA",
        "India":"IND",
        "Iran":"IRI",
        "Ireland":"IRL",
        "Iraq":"IRQ",
        "Iceland":"ISL",
        "Israel":"ISR",
        "Virgin Islands":"ISV",
        "Italy":"ITA",
        "British Virgin Islands":"IVB",
        "Jamaica":"JAM",
        "Jordan":"JOR",
        "Japan":"JPN",
        "Kazakhstan":"KAZ",
        "Kenya":"KEN",
        "Kyrgyzstan":"KGZ",
        "Kiribati":"KIR",
        "South Korea":"KOR",
        "Saudi Arabia":"KSA",
        "Kuwait":"KUW",
        "Laos":"LAO",
        "Latvia":"LAT",
        "Libya":"LBA",
        "Liberia":"LBR",
        "Saint Lucia":"LCA",
        "Lesotho":"LES",
        "Lebanon":"LIB",
        "Liechtenstein":"LIE",
        "Lithuania":"LTU",
        "Luxembourg":"LUX",
        "Madagascar":"MAD",
        "Morocco":"MAR",
        "Malaysia":"MAS",
        "Malawi":"MAW",
        "Moldova":"MDA",
        "Maldives":"MDV",
        "Mexico":"MEX",
        "Mongolia":"MGL",
        "Marshall Islands":"MHL",
        "Macedonia":"MKD",
        "Mali":"MLI",
        "Malta":"MLT",
        "Montenegro":"MNE",
        "Monaco":"MON",
        "Mozambique":"MOZ",
        "Mauritius":"MRI",
        "Mauritania":"MTN",
        "Myanmar":"MYA",
        "Namibia":"NAM",
        "Nicaragua":"NCA",
        "Netherlands":"NED",
        "Nepal":"NEP",
        "Nigeria":"NGR",
        "Niger":"NIG",
        "Norway":"NOR",
        "Nauru":"NRU",
        "New Zealand":"NZL",
        "Oman":"OMA",
        "Pakistan":"PAK",
        "Panama":"PAN",
        "Paraguay":"PAR",
        "Peru":"PER",
        "Philippines":"PHI",
        "Palestine":"PLE",
        "Palau":"PLW",
        "Papua New Guinea":"PNG",
        "Poland":"POL",
        "Portugal":"POR",
        "North Korea":"PRK",
        "Puerto Rico":"PUR",
        "Qatar":"QAT",
        "Romania":"ROU",
        "South Africa":"RSA",
        "Russia":"RUS",
        "Rwanda":"RWA",
        "Samoa":"SAM",
        "Senegal":"SEN",
        "Seychelles":"SEY",
        "Singapore":"SIN",
        "Saint Kitts and Nevis":"SKN",
        "Sierra Leone":"SLE",
        "Slovenia":"SLO",
        "San Marino":"SMR",
        "Solomon Islands":"SOL",
        "Somalia":"SOM",
        "Serbia":"SRB",
        "Sri Lanka":"SRI",
        "São Tomé and Príncipe":"STP",
        "Sudan":"SUD",
        "Switzerland":"SUI",
        "Suriname":"SUR",
        "Slovakia":"SVK",
        "Sweden":"SWE",
        "Swaziland":"SWZ",
        "Syria":"SYR",
        "Tanzania":"TAN",
        "Tonga":"TGA",
        "Thailand":"THA",
        "Tajikistan":"TJK",
        "Turkmenistan":"TKM",
        "Timor-Leste":"TLS",
        "Togo":"TOG",
        "Chinese Taipei[5]":"TPE",
        "Trinidad and Tobago":"TTO",
        "Tunisia":"TUN",
        "Turkey":"TUR",
        "Tuvalu":"TUV",
        "United Arab Emirates":"UAE",
        "Uganda":"UGA",
        "Ukraine":"UKR",
        "Uruguay":"URU",
        "United States":"USA",
        "Uzbekistan":"UZB",
        "Vanuatu":"VAN",
        "Venezuela":"VEN",
        "Vietnam":"VIE",
        "Saint Vincent and the Grenadines":"VIN",
        "Yemen":"YEM",
        "Zambia":"ZAM",
        "Zimbabwe":"ZIM"}

def GetCountryCode(nom_pays):
    return (Pays.get(nom_pays))
